-- DDL for task registry (H2)

CREATE TABLE IF NOT EXISTS executors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    state VARCHAR(32) NOT NULL,
    successful_tasks_count BIGINT NOT NULL DEFAULT 0,
    error_tasks_count BIGINT NOT NULL DEFAULT 0,
    aborted_tasks_count BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(32) NOT NULL,
    executor_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    status VARCHAR(32) NOT NULL,
    completion_percent BIGINT NOT NULL,
    formula VARCHAR(4000),
    CONSTRAINT fk_tasks_executor FOREIGN KEY (executor_id) REFERENCES executors(id)
);

CREATE TABLE IF NOT EXISTS task_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    message VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_logs_task FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE TABLE IF NOT EXISTS task_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(32) NOT NULL,
    formula VARCHAR(4000),
    next_run_at TIMESTAMP NOT NULL,
    repeat_interval_minutes BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_triggered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);
