spring.application.name=scheduler-service

server.port=8082

spring.datasource.url=jdbc:h2:file:./data/schedulerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

scheduler.enabled=true
scheduler.poll-interval-ms=5000

app.kafka.task-create-topic=task.create

spring.kafka.bootstrap-servers=localhost:9092
