spring.application.name=gateway

server.port=8080

spring.web.resources.static-locations=classpath:/static/

spring.cloud.gateway.server.webflux.routes[0].id=auth
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=schedules
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/schedules/**

spring.cloud.gateway.server.webflux.routes[2].id=tasks
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/**
